basePath: /api
definitions:
  handler.Response:
    properties:
      code:
        description: Code 状态码，非0时表示自定义HTTP业务状态码
        type: integer
      data:
        description: Data 响应数据，具体内容因接口而异
      msg:
        description: Msg 返回信息，通常是状态描述
        type: string
    type: object
  model.LoginDto:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  model.RegisterDto:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  model.UserInfoDto:
    properties:
      avatar:
        description: |-
          头像地址
          example: https://example.com/avatar.png
        type: string
      is_admin:
        description: |-
          是否为管理员
          example: false
        type: boolean
      password:
        description: |-
          密码
          example: 123456
        type: string
      username:
        description: |-
          用户名
          example: linsnow
        type: string
    type: object
host: localhost:6277
info:
  contact: {}
  description: 开源、自托管轻量级发布平台 Ech0 的 API 文档
  title: Ech0 API 文档
  version: "1.0"
paths:
  /allusers:
    get:
      consumes:
      - application/json
      description: 获取系统中所有用户的详细信息，接口需要认证
      produces:
      - application/json
      responses:
        "200":
          description: 获取失败，code=0，msg错误描述
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取所有用户
      tags:
      - 用户管理
  /login:
    post:
      consumes:
      - application/json
      description: 用户通过用户名和密码登录，返回 JWT Token
      parameters:
      - description: 登录请求体
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/model.LoginDto'
      produces:
      - application/json
      responses:
        "200":
          description: 登录失败，返回错误信息
          schema:
            $ref: '#/definitions/handler.Response'
      summary: 用户登录接口
      tags:
      - 用户认证
  /register:
    post:
      consumes:
      - application/json
      description: 通过提交用户名、密码等信息完成注册
      parameters:
      - description: 注册请求体
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/model.RegisterDto'
      produces:
      - application/json
      responses:
        "200":
          description: 请求参数错误或注册失败，code=0，msg错误描述
          schema:
            $ref: '#/definitions/handler.Response'
      summary: 用户注册
      tags:
      - 用户认证
  /user:
    get:
      consumes:
      - application/json
      description: 获取当前认证用户的详细信息，密码字段不会返回
      produces:
      - application/json
      responses:
        "200":
          description: 获取失败，code=0，msg错误描述
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取当前用户信息
      tags:
      - 用户管理
    put:
      consumes:
      - application/json
      description: 接口会根据请求体更新用户相关字段，需携带有效的用户身份（如 JWT）
      parameters:
      - description: 用户更新信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserInfoDto'
      produces:
      - application/json
      responses:
        "200":
          description: 请求参数错误或更新失败，code=0，msg错误描述
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - ApiKeyAuth: []
      summary: 更新当前用户的信息
      tags:
      - 用户管理
  /user/{id}:
    delete:
      consumes:
      - application/json
      description: 根据用户ID删除用户，调用者需具备相应权限
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 参数错误或删除失败，code=0，msg错误描述
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - ApiKeyAuth: []
      summary: 删除用户
      tags:
      - 用户管理
  /user/admin/{id}:
    put:
      consumes:
      - application/json
      description: 通过用户ID更新其管理员权限，接口调用者需拥有相应权限
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 参数错误或更新失败，code=0，msg错误描述
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - ApiKeyAuth: []
      summary: 更新用户权限（管理员权限）
      tags:
      - 用户管理
swagger: "2.0"
